// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpUv_zs8AEsxh6fvDztCgyfLK81zfU1TM',
    appId: '1:318231201906:web:0efb9fdcb616b2c0ecdaeb',
    messagingSenderId: '318231201906',
    projectId: 'fir-concept-5d6f5',
    authDomain: 'fir-concept-5d6f5.firebaseapp.com',
    storageBucket: 'fir-concept-5d6f5.firebasestorage.app',
    measurementId: 'G-6XFHWPLBP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGWn--OnbEuBOj7QjtA7l8pmEx8Mc0yWk',
    appId: '1:318231201906:android:d58d965a277f5aefecdaeb',
    messagingSenderId: '318231201906',
    projectId: 'fir-concept-5d6f5',
    storageBucket: 'fir-concept-5d6f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4N79o7zbTCJHG_50nSoe3W3JQMcsfVTA',
    appId: '1:318231201906:ios:afe1efd9b5b65a62ecdaeb',
    messagingSenderId: '318231201906',
    projectId: 'fir-concept-5d6f5',
    storageBucket: 'fir-concept-5d6f5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConcept',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4N79o7zbTCJHG_50nSoe3W3JQMcsfVTA',
    appId: '1:318231201906:ios:afe1efd9b5b65a62ecdaeb',
    messagingSenderId: '318231201906',
    projectId: 'fir-concept-5d6f5',
    storageBucket: 'fir-concept-5d6f5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConcept',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpUv_zs8AEsxh6fvDztCgyfLK81zfU1TM',
    appId: '1:318231201906:web:2604015c98f21c8fecdaeb',
    messagingSenderId: '318231201906',
    projectId: 'fir-concept-5d6f5',
    authDomain: 'fir-concept-5d6f5.firebaseapp.com',
    storageBucket: 'fir-concept-5d6f5.firebasestorage.app',
    measurementId: 'G-6X62C6HH7Z',
  );
}
